server:
  port: 10000
korail:
  service-key: VbGT1gAGtB0pWwVeEzwW/a3QsjZx5CnJrEwi4qXcekuJRem4Eai2V/NbbjlbVUh3DlxMu0Pg94aJrjOFqFryAQ==
bus:
  service-key: VbGT1gAGtB0pWwVeEzwW/a3QsjZx5CnJrEwi4qXcekuJRem4Eai2V/NbbjlbVUh3DlxMu0Pg94aJrjOFqFryAQ==
kakao:
  api-key: 8f8539e18dbd6168eaf2123a48a02fa0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tripmate?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  jwtSecret: your-super-long-secret-key-which-is-safe-and-over-64-bytes-long...
  jwtExpirationInMs: 86400000 