korail:
  service-key: wNxypnQAgMo%2BNSvrqNGmcCUMD%2BnMiRssn%2BxaPUBDgWn7%2BZjCaHQdBPrdAjhkFdjkwpsRZ5ydbAjf3XSIcSPSfQ%3D%3D
bus:
  service-key: wNxypnQAgMo%2BNSvrqNGmcCUMD%2BnMiRssn%2BxaPUBDgWn7%2BZjCaHQdBPrdAjhkFdjkwpsRZ5ydbAjf3XSIcSPSfQ%3D%3D
kakao:
  api-key: d9ede708e331a6006963927991200ee3